language: php

php:
    - 5.6

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/phpunit -c phpunit.xml --colors --coverage-clover=build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml